In [14]:
import numpy as np

In [15]:
list1 = [1,2,3,4,5]
print(list1[0])

1


In [16]:
def model1(metrage: int) -> int:
    price = metrage * 1000
    return price

def model2(metrage, price):
    if price > 400000:
        result = "Iran"
    elif price > 300000:
        result = "USA"
    else:
        result = "India"
    return result

# Input
input_metrage = 500

# Prediction
predicted_price = model1(input_metrage)

predicted_country = model2(input_metrage, predicted_price)
predicted_country = model2(input_metrage, input_metrage * 1000)


In [17]:
# Data
# X:   x0 x1 x2      y
# X_1:  1  4  5     10
# X_2:  3 -5  6      1
# X_3:  2  0 10      6
# X_4: -5 12  3     -4

X_1 = np.array([1,4,5]) 
X_2 = np.array([3, -5, 6])
X_3 = np.array([2, 0, 10])
X_4 = np.array([-5, 12, 3])
X = np.array([ X_1, X_2, X_3, X_4 ])

print(X)

[[ 1  4  5]
 [ 3 -5  6]
 [ 2  0 10]
 [-5 12  3]]


In [18]:
# Tuple
tuple1 = (97,2)

tuple1[1]

2

In [19]:
def my_load_data():
    data = np.loadtxt("ex1data1.txt", delimiter=',')
    return data

data1 = my_load_data()
print("Shape of data1: ", data1.shape)

data2 = np.ndarray((10, 3)) # 10 x 3
print("data2: ", data2)

Shape of data1:  (97, 2)
data2:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x_train = data1[:,0]
y_train = data1[:,1]

In [21]:
x_train.shape

# 1-dim -> shape (dim1)
# 2-dim -> shape (dim1, dim2)
# 3-dim -> shape (dim1, dim2, dim3)
# ...
# 1000-dim -> shape (dim1, dim2, ..., dim1000)

(97,)

In [22]:
(97,2,100)[2]

100